/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author alumno
 */
public class PantallaPrincipal extends javax.swing.JFrame {
LogicaNegocio lg= new LogicaNegocio();
private TableRowSorter<IngresoGastoTableModel>sorter;
 private TableRowSorter<IngresoGastoTableModel>sort;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        jTableIngreso.setModel(new IngresoGastoTableModel(LogicaNegocio.mostrarListaIngreso()));
        jTablegasto.setModel(new IngresoGastoTableModel(LogicaNegocio.mostrarListaGasto()));
      IngresoGastoTableModel itm= new IngresoGastoTableModel(LogicaNegocio.mostrarListaIngreso());
        IngresoGastoTableModel gtm= new IngresoGastoTableModel(LogicaNegocio.mostrarListaGasto());
        //para ordenar
        //primera tabla
        sorter = new TableRowSorter<>(itm);
        jTableIngreso.setRowSorter(sorter);
        //segunda tabla
        sort= new TableRowSorter<>(gtm);
        jTablegasto.setRowSorter(sort);
        //ordenar por un campo
        List<RowSorter.SortKey> sortKeys= new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(0,SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        sort.setSortKeys(sortKeys);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIngreso = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotalIngreso = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablegasto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGastoTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBalance = new javax.swing.JTextField();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonfiltrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItemIngreso = new javax.swing.JCheckBoxMenuItem();
        jMenuItemGasto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIngreso);

        jLabel1.setText("Ingreso Total:");

        jTablegasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablegasto);

        jLabel2.setText("Gasto total:");

        jLabel3.setText("Balance");

        jButtonfiltrar.setText("Filtro");
        jButtonfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfiltrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Gestion");

        jCheckBoxMenuItemIngreso.setSelected(true);
        jCheckBoxMenuItemIngreso.setText("Ingreso");
        jCheckBoxMenuItemIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemIngresoActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItemIngreso);

        jMenuItemGasto.setText("Gasto");
        jMenuItemGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGastoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGasto);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalIngreso))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGastoTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBalance)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonfiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotalIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldGastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonfiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFiltro))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemIngresoActionPerformed
         PantallaIngreso pantallaalta= new PantallaIngreso(this, true);
       pantallaalta.setVisible(true);
       refrescarTablaIngreso();
       lg.ingresototal();
       jTextFieldTotalIngreso.setText(Float.toString(lg.getIngresototal()));
       lg.Balance();
        jTextFieldBalance.setText(Float.toString(lg.Balance()));
       if(lg.getTotal()>=0){
           setEnabled(true);
           jTextFieldBalance.setForeground(Color.green);
           jTextFieldBalance.setText(Float.toString(lg.Balance()));
       
       }
    }//GEN-LAST:event_jCheckBoxMenuItemIngresoActionPerformed

    private void jMenuItemGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGastoActionPerformed
     PantallaGasto pantallagasto= new PantallaGasto(this,true);
     pantallagasto.setVisible(true);
    refrescarTablaGasto();
     lg.gastoTotal();
     jTextFieldGastoTotal.setText(Float.toString(lg.getGastototal()));
        lg.Balance();
     jTextFieldBalance.setText(Float.toString(lg.Balance()));
     if(lg.getTotal()< 0){
         jTextFieldBalance.setEnabled(true);
     jTextFieldBalance.setForeground(Color.red);
     jTextFieldBalance.setText(Float.toString(lg.Balance()));
    
     }
    
    }//GEN-LAST:event_jMenuItemGastoActionPerformed

    private void jButtonfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfiltrarActionPerformed
          RowFilter<IngresoGastoTableModel,Integer> rf= RowFilter.regexFilter(jTextFieldFiltro.getText(), 1);
          sorter.setRowFilter(rf);
           sort.setRowFilter(rf);
    }//GEN-LAST:event_jButtonfiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }
    //metodo redfrescar 
    private void refrescarTablaIngreso(){
    IngresoGastoTableModel itm= (IngresoGastoTableModel)jTableIngreso.getModel();
    itm.refrescar();
    }
    private void refrescarTablaGasto(){
    IngresoGastoTableModel gtm=(IngresoGastoTableModel)jTablegasto.getModel();
    gtm.refrescar();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonfiltrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemGasto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableIngreso;
    private javax.swing.JTable jTablegasto;
    private javax.swing.JTextField jTextFieldBalance;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldGastoTotal;
    private javax.swing.JTextField jTextFieldTotalIngreso;
    // End of variables declaration//GEN-END:variables
}
